# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install cmake libgtest-dev
      - run: mkdir build && cd build && cmake .. && ./test_check_cicd
        